# Generated by Django 3.2.6 on 2022-03-12 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockproduct',
            unique_together={('stock', 'product')},
        ),
    ]
