# Generated by Django 3.2.6 on 2022-03-12 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0003_alter_stockproduct_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockproduct',
            unique_together={('stock', 'product')},
        ),
    ]
